// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

import "./DeployHelpers.s.sol";
import "../contracts/PenumbraAuction.sol";
import "../contracts/NullifierVerifier.sol";

contract DeployPenumbraAuction is ScaffoldETHDeploy {
    function run() external ScaffoldEthDeployerRunner {
        // 1. Deploy the ZK verifier contract (generated by Barretenberg)
        HonkVerifier verifier = new HonkVerifier();
        console.log("HonkVerifier (ZK Verifier) deployed at:", address(verifier));
        deployments.push(Deployment("HonkVerifier", address(verifier)));

        // 2. Deploy the auction contract with the verifier address
        PenumbraAuction auction = new PenumbraAuction(deployer, address(verifier));
        console.log("PenumbraAuction deployed at:", address(auction));
        deployments.push(Deployment("PenumbraAuction", address(auction)));
    }
}
